---
services:
  frontend:
    container_name: beads-and-bid-frontend
    image: ghcr.io/lewynation/beads_and_bid_frontend:sha-59b0387
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - beads_and_bid
    ports:
      - "3000:6061"
    environment:
      - DATABASE_URL=postgresql://root:root@pg:5432/home_gym?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - GOOGLE_CLIENT_ID=879539022198-uvhmqkk06u59d87sumf4qd56ei4heur5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      # - MPESA
      - MPESA_BUSINESS_SHORT_CODE=
      - MPESA_TRANSACTION_TYPE=CustomerPayBillOnline
      - MPESA_CALLBACK_BASE_URL=http://localhost:3000/api/payments
      - MPESA_PASSKEY=passkey
      - MPESA_STK_PUSH_URL=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
      - MPESA_CONSUMER_KEY=consumerKey
      - MPESA_CONSUMER_SECRET=consumerSecret
      - MPESA_AUTH_URL=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
      # - callback socket gateway
      - SOCKET_GATEWAY_WEBHOOk_URL=http://gym-backend:3001/webhook/payments
      # Main
      - NOMEMAIL_USER=mark_test29@outlook.com
      - NOMEMAIL_PASS=100%assignmenttest.

  postgres:
    container_name: pg
    image: postgres:latest
    restart: always
    networks:
      - beads_and_bid
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - beads_and_bid
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./volumes/pgadmin:/root/.pgadmin
    ports:
      - "5050:80"

networks:
  beads_and_bid:
    external: true
