version: "3"
services:
  database_migrator:
    container_name: database-migrator
    image: ghcr.io/lewynation/beads_and_bid_database_migrator:sha-59b0387
    environment:
      - DATABASE_URL="postgresql://root:root@pg:5432/beads_and_bid?schema=public"
    networks:
      - beads_and_bid
    command: sh
    stdin_open: true
    tty: true

networks:
  beads_and_bid:
    external: true
